import { BuildingType } from './buildings';
import type { BuildingDef } from './buildings';

export const BUILDING_DEFS: Record<BuildingType, BuildingDef> = {
  [BuildingType.HOUSE]: {
    type: BuildingType.HOUSE,
    name: 'Casa / Cabaña',
    emoji: '🏠',
    cost: { food: 40, gold: 15, stone: 30 },
    buildTime: 7,
    maxHp: 80,
    buildRadius: 2,
    description: 'Vivienda para tus súbditos. Cada casa aumenta el límite de población en +12 unidades.',
  },
  [BuildingType.SETTLEMENT]: {
    type: BuildingType.SETTLEMENT,
    name: 'Nuevo Asentamiento',
    emoji: '🏘️',
    cost: { food: 250, gold: 200, stone: 300 },
    buildTime: 30,
    maxHp: 200,
    buildRadius: 4,
    description: 'Funda un nuevo asentamiento lejos de tu base. Permite expandir tu territorio y entrenar trabajadores allí.',
  },
  [BuildingType.FARM]: {
    type: BuildingType.FARM,
    name: 'Granja / Milpa',
    emoji: '🌾',
    cost: { food: 50, gold: 20, stone: 0 },
    buildTime: 10,
    maxHp: 90,
    buildRadius: 2,
    description: 'Cultiva milpa o chacra. Genera +50🌽 de producción pasiva en cada ciclo económico. Construye varias para sostener un gran ejército.',
  },
  [BuildingType.BARRACKS]: {
    type: BuildingType.BARRACKS,
    name: 'Cuartel',
    emoji: '🏛️',
    cost: { food: 75, gold: 100, stone: 100 },
    buildTime: 20,
    maxHp: 150,
    buildRadius: 3,
    description: 'Entrena unidades militares avanzadas. Mejora con tecnología.',
  },
  [BuildingType.TEMPLE]: {
    type: BuildingType.TEMPLE,
    name: 'Templo',
    emoji: '🛕',
    cost: { food: 50, gold: 150, stone: 150 },
    buildTime: 25,
    maxHp: 180,
    buildRadius: 4,
    description: 'Investiga tecnología y otorga poder especial a la civilización.',
  },
  [BuildingType.WATCHTOWER]: {
    type: BuildingType.WATCHTOWER,
    name: 'Torre de Vigilancia',
    emoji: '🗼',
    cost: { food: 50, gold: 75, stone: 125 },
    buildTime: 12,
    maxHp: 120,
    buildRadius: 2,
    description: 'Defensa activa. Ataca enemigos en rango.',
  },
  [BuildingType.STOREHOUSE]: {
    type: BuildingType.STOREHOUSE,
    name: 'Almacén',
    emoji: '📦',
    cost: { food: 60, gold: 40, stone: 80 },
    buildTime: 10,
    maxHp: 140,
    buildRadius: 3,
    description: 'Aumenta la capacidad de almacenamiento de recursos en +200 cada uno.',
  },
  [BuildingType.FORGE]: {
    type: BuildingType.FORGE,
    name: 'Herrería',
    emoji: '⚒️',
    cost: { food: 80, gold: 120, stone: 100 },
    buildTime: 18,
    maxHp: 160,
    buildRadius: 3,
    description: 'Mejora armas y armaduras. Funde mineral: convierte 🪵→⚫ carbón y 🪨→🔩 hierro para la pólvora.',
  },
  [BuildingType.WONDER]: {
    type: BuildingType.WONDER,
    name: 'Gran Maravilla',
    emoji: '🏛️',
    cost: { food: 250, gold: 500, stone: 350 },
    buildTime: 120,
    maxHp: 500,
    buildRadius: 5,
    description: 'Obra monumental de tu civilización. Complétala y defiéndela 3 minutos para alcanzar la gloria.',
  },
  [BuildingType.VILLAGE]: {
    type: BuildingType.VILLAGE,
    name: 'Aldea Neutral',
    emoji: '🏡',
    cost: { food: 0, gold: 0, stone: 0 },
    buildTime: 0,
    maxHp: 80,
    buildRadius: 2,
    description: 'Aldea preexistente. Captúrala con tropas cuerpo a cuerpo para recibir +10🌽 y +6⚜️ cada 30s.',
  },
  [BuildingType.HARBOR]: {
    type: BuildingType.HARBOR,
    name: 'Puerto',
    emoji: '⚓',
    cost: { food: 80, gold: 150, stone: 100 },
    buildTime: 22,
    maxHp: 130,
    buildRadius: 3,
    description: 'Construye y repara unidades navales. Debe edificarse junto al agua.',
  },
  [BuildingType.MARKET]: {
    type: BuildingType.MARKET,
    name: 'Mercado',
    emoji: '🏪',
    cost: { food: 60, gold: 80, stone: 60 },
    buildTime: 14,
    maxHp: 110,
    buildRadius: 3,
    description: 'Centro comercial. Vende comida, madera y piedra por oro. Genera +5⚜️ pasivos cada 60s.',
  },
  [BuildingType.WALL]: {
    type: BuildingType.WALL,
    name: 'Muralla',
    emoji: '🧱',
    cost: { food: 0, gold: 40, stone: 200 },
    buildTime: 10,
    maxHp: 400,
    buildRadius: 1,
    description: 'Barrera defensiva de piedra. Alta resistencia al daño. Las unidades no pueden atravesarla.',
  },
  [BuildingType.GATE]: {
    type: BuildingType.GATE,
    name: 'Puerta',
    emoji: '🚪',
    cost: { food: 0, gold: 60, stone: 150 },
    buildTime: 10,
    maxHp: 320,
    buildRadius: 1,
    description: 'Puerta fortificada. Mismo blindaje que la muralla pero deja pasar a las tropas: úsala como acceso controlado en tus murallas.',
  },
};
