import { BuildingType } from './buildings';
import type { BuildingDef } from './buildings';

export const BUILDING_DEFS: Record<BuildingType, BuildingDef> = {
  [BuildingType.SETTLEMENT]: {
    type: BuildingType.SETTLEMENT,
    name: 'Asentamiento',
    emoji: '🏘️',
    cost: { food: 100, gold: 50, stone: 75 },
    buildTime: 15,
    maxHp: 200,
    buildRadius: 4,
    description: 'Centro urbano. Produce trabajadores y proporciona control territorial.',
  },
  [BuildingType.BARRACKS]: {
    type: BuildingType.BARRACKS,
    name: 'Cuartel',
    emoji: '🏛️',
    cost: { food: 75, gold: 100, stone: 100 },
    buildTime: 20,
    maxHp: 150,
    buildRadius: 3,
    description: 'Entrena unidades militares avanzadas. Mejora con tecnología.',
  },
  [BuildingType.TEMPLE]: {
    type: BuildingType.TEMPLE,
    name: 'Templo',
    emoji: '🛕',
    cost: { food: 50, gold: 150, stone: 150 },
    buildTime: 25,
    maxHp: 180,
    buildRadius: 4,
    description: 'Investiga tecnología y otorga poder especial a la civilización.',
  },
  [BuildingType.WATCHTOWER]: {
    type: BuildingType.WATCHTOWER,
    name: 'Torre de Vigilancia',
    emoji: '🗼',
    cost: { food: 50, gold: 75, stone: 125 },
    buildTime: 12,
    maxHp: 120,
    buildRadius: 2,
    description: 'Defensa activa. Ataca enemigos en rango.',
  },
  [BuildingType.STOREHOUSE]: {
    type: BuildingType.STOREHOUSE,
    name: 'Almacén',
    emoji: '📦',
    cost: { food: 60, gold: 40, stone: 80 },
    buildTime: 10,
    maxHp: 140,
    buildRadius: 3,
    description: 'Aumenta la capacidad de almacenamiento de recursos en +200 cada uno.',
  },
  [BuildingType.FORGE]: {
    type: BuildingType.FORGE,
    name: 'Herrería',
    emoji: '⚒️',
    cost: { food: 80, gold: 120, stone: 100 },
    buildTime: 18,
    maxHp: 160,
    buildRadius: 3,
    description: 'Mejora armas y armaduras. Aumenta ataque/defensa de unidades.',
  },
  [BuildingType.WONDER]: {
    type: BuildingType.WONDER,
    name: 'Gran Maravilla',
    emoji: '🏛️',
    cost: { food: 250, gold: 500, stone: 350 },
    buildTime: 120,
    maxHp: 500,
    buildRadius: 5,
    description: 'Obra monumental de tu civilización. Complétala y defiéndela 3 minutos para alcanzar la gloria.',
  },
};
